spring.application.name=Backend_WebBasedSubscriptionAndBillingSystem
spring.datasource.url=jdbc:postgresql://localhost:5432/subscription_billing_new
spring.datasource.username=postgres
spring.datasource.password=postgres18
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

#spring.security.user.name=root
#spring.security.user.password=root@123
#For Swagger Api Testing Link
#http://localhost:8080/swagger-ui/index.html

jwt.secret=ThisIsMyVeryStrongSecretKeyForSubscriptionBillingSystem2026
jwt.expiration=86400000
jwt.refresh-expiration=604800000

server.port=8080

#Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
#spring.mail.username=Email
#spring.mail.password=Code

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true